package jetlin.db.ksp

/**
 * The generated code.
 *
 * Fully qualified names throughout, and no imports: generated code has no reader to please and every
 * import is a way for it to collide with something the entity's own file declared.
 *
 * Kept as pure string building so the output can be asserted in a unit test. The alternative —
 * checking generated code by compiling it — only tells you that *something* compiled.
 */
internal fun emitTable(entity: EntityModel): String = buildString {
    val type = entity.qualifiedName
    appendLine("// Generated by jetlin-db-ksp from $type. Do not edit.")
    appendLine("@file:Suppress(\"RedundantVisibilityModifier\", \"unused\")")
    appendLine()
    if (entity.packageName.isNotEmpty()) {
        appendLine("package ${entity.packageName}")
        appendLine()
    }

    appendLine("/**")
    appendLine(" * How [$type] is stored, and the columns a policy can name.")
    appendLine(" *")
    appendLine(" * A column here is the object the table flushes, so `when (column)` in a policy matches.")
    appendLine(" */")
    appendLine("${entity.visibility} object ${entity.objectName} {")
    appendLine()
    appendLine("    ${entity.visibility} val policy: jetlin.db.Policy<$type, ${entity.principal}> = $type")
    appendLine()
    appendLine("    ${entity.visibility} val table: jetlin.db.Table<$type> =")
    appendLine("        jetlin.db.table(\"${entity.tableName}\", $type::class) {")
    entity.columns.forEach { column -> appendLine("            ${declare(column)}") }
    appendLine("            load { row ->")
    appendLine(loadBody(entity).trimEnd().prependIndent("                "))
    appendLine("            }")
    appendLine("        }")
    entity.columns.forEach { column ->
        appendLine()
        appendLine("    ${entity.visibility} val ${column.name}: jetlin.db.Column<$type> =")
        appendLine("        table.column(\"${column.name}\")")
    }
    appendLine()
    append(emitAccessors(entity))
    appendLine("}")
    appendLine()
    append(emitDraft(entity))
    appendLine()
    append(emitMutators(entity))
}

/**
 * The only way application code obtains one of these records.
 *
 * Every one takes the principal as a context parameter, so a page that forgot to have a principal in scope
 * does not compile rather than quietly reading someone else's rows.
 */
private fun emitAccessors(entity: EntityModel): String = buildString {
    val type = entity.qualifiedName
    val principal = entity.principal
    appendLine("    /** Every stored ${entity.simpleName} this principal may read. */")
    appendLine("    context(principal: $principal)")
    appendLine("    ${entity.visibility} fun all(db: jetlin.db.Db): jetlin.db.View<$type> =")
    appendLine("        jetlin.db.Gate.view(db, table, policy, principal)")
    appendLine()
    appendLine("    /** The ${entity.simpleName} with this id, or null — including when it exists and is not readable. */")
    appendLine("    context(principal: $principal)")
    appendLine("    ${entity.visibility} fun find(db: jetlin.db.Db, id: jetlin.db.Id<$type>): $type? =")
    appendLine("        jetlin.db.Gate.find(db, table, policy, principal, id)")
}

/**
 * `update { }` and `delete()`, as extensions carrying the principal.
 *
 * Assignment straight to a field was considered and rejected: a property setter has nowhere to put a
 * context parameter, so `todo.done = true` could only be checked against an ambient principal at runtime.
 * `update { }` costs eight characters and keeps the guarantee at compile time.
 */
private fun emitMutators(entity: EntityModel): String = buildString {
    val type = entity.qualifiedName
    val principal = entity.principal
    appendLine("/**")
    appendLine(" * Changes this ${entity.simpleName} as one transaction: committed to disk before any session sees it.")
    appendLine(" *")
    appendLine(" * Refused writes throw [jetlin.db.AccessDenied]; a refusal inside a transaction commits nothing.")
    appendLine(" */")
    appendLine("context(principal: $principal)")
    appendLine("${entity.visibility} fun $type.update(block: ${entity.draftQualified}.() -> Unit) {")
    appendLine("    val row = this")
    appendLine("    jetlin.db.Gate.update(row, ${entity.objectQualified}.policy, principal) {")
    appendLine("        ${entity.draftQualified}(row, principal).block()")
    appendLine("    }")
    appendLine("}")
    appendLine()
    appendLine("/** Removes this ${entity.simpleName}, if this principal may delete it. */")
    appendLine("context(principal: $principal)")
    appendLine("${entity.visibility} fun $type.delete(): Unit =")
    appendLine("    jetlin.db.Gate.delete(this, ${entity.objectQualified}.policy, principal)")
}

private fun declare(column: ColumnModel): String {
    val nullable = ", nullable = ${column.nullable}"
    val get = "{ it.${column.name} }"
    return when {
        column.reference != null ->
            "reference(\"${column.name}\", ${column.reference}::class$nullable) $get"
        column.kind == SqlKind.Text -> "text(\"${column.name}\"$nullable) $get"
        column.kind == SqlKind.Bool -> "bool(\"${column.name}\"$nullable) $get"
        column.kind == SqlKind.Real -> "real(\"${column.name}\"$nullable) $get"
        else -> "integer(\"${column.name}\"$nullable) $get"
    }
}

/** How one column is read back out of a stored row. */
private fun read(column: ColumnModel): String {
    val name = "\"${column.name}\""
    return when {
        column.reference != null -> when {
            column.nullable -> "row.referenceOrNull($name, ${column.reference}::class)"
            else -> "row.reference($name, ${column.reference}::class)"
        }
        column.kind == SqlKind.Text -> if (column.nullable) "row.stringOrNull($name)" else "row.string($name)"
        column.kind == SqlKind.Bool ->
            if (column.nullable) "row.booleanOrNull($name)" else "row.boolean($name)"
        column.kind == SqlKind.Real -> when (column.baseType) {
            "kotlin.Float" ->
                if (column.nullable) "row.doubleOrNull($name)?.toFloat()" else "row.double($name).toFloat()"
            else -> if (column.nullable) "row.doubleOrNull($name)" else "row.double($name)"
        }
        else -> when (column.baseType) {
            "kotlin.Int" -> if (column.nullable) "row.intOrNull($name)" else "row.int($name)"
            else -> if (column.nullable) "row.longOrNull($name)" else "row.long($name)"
        }
    }
}

/**
 * Rebuilds one record from a row: constructor first, then whatever the constructor does not take.
 *
 * Columns the constructor accepts go through it, so an immutable column and a `val` cell both work.
 * What is left over must be settable, which [validate] has already established.
 */
private fun loadBody(entity: EntityModel): String = buildString {
    val byConstructor = entity.columns.filter { it.constructorParameter }
    val afterwards = entity.columns.filterNot { it.constructorParameter }

    append(entity.qualifiedName).appendLine("(")
    byConstructor.forEach { column -> appendLine("    ${column.name} = ${read(column)},") }
    append(")")
    if (afterwards.isEmpty()) {
        appendLine()
    } else {
        appendLine(".also { entity ->")
        afterwards.forEach { column -> appendLine("    entity.${column.name} = ${read(column)}") }
        appendLine("}")
    }
}

/**
 * The draft type `update { }` hands to the caller.
 *
 * Only settable columns appear: an immutable one is written once, by the insert, and there is nothing a
 * draft could do with it. The column-level policy check lands in these setters in phase 4 — which is
 * the whole reason a draft exists rather than assignment straight to the record.
 */
private fun emitDraft(entity: EntityModel): String = buildString {
    val settable = entity.columns.filter { it.settable }
    appendLine("/**")
    appendLine(" * The fields of a [${entity.qualifiedName}] that `update { }` may write.")
    appendLine(" */")
    appendLine("${entity.visibility} class ${entity.draftName} internal constructor(")
    appendLine("    private val row: ${entity.qualifiedName},")
    appendLine("    private val principal: ${entity.principal},")
    appendLine(") {")
    settable.forEachIndexed { index, column ->
        if (index > 0) appendLine()
        appendLine("    ${entity.visibility} var ${column.name}: ${column.declaredType}")
        appendLine("        get() = row.${column.name}")
        appendLine("        set(value) {")
        appendLine("            jetlin.db.Gate.requireWrite(")
        appendLine("                row,")
        appendLine("                ${entity.objectName}.${column.name},")
        appendLine("                ${entity.objectName}.policy,")
        appendLine("                principal,")
        appendLine("            )")
        appendLine("            row.${column.name} = value")
        appendLine("        }")
    }
    if (settable.isEmpty()) {
        appendLine("    // Nothing on ${entity.simpleName} is settable: every column is written by the insert.")
    }
    appendLine("}")
}

/**
 * The list of tables, in load order.
 *
 * An application passes this to `Db.open`, so the order non-null references require is part of the
 * generated schema rather than something to get right by hand.
 */
internal fun emitSchema(entities: List<EntityModel>, packageName: String, objectName: String): String =
    buildString {
        appendLine("// Generated by jetlin-db-ksp. Do not edit.")
        appendLine("@file:Suppress(\"RedundantVisibilityModifier\", \"unused\")")
        appendLine()
        if (packageName.isNotEmpty()) {
            appendLine("package $packageName")
            appendLine()
        }
        val visibility = if (entities.any { it.isInternal }) "internal" else "public"
        appendLine("/**")
        appendLine(" * Every stored entity, ordered so that a table is loaded after the tables it references.")
        appendLine(" */")
        appendLine("$visibility object $objectName {")
        appendLine("    $visibility val tables: List<jetlin.db.Table<out jetlin.db.Record>> = listOf(")
        entities.forEach { entity ->
            val qualifier = if (entity.packageName == packageName || entity.packageName.isEmpty()) {
                entity.objectName
            } else {
                "${entity.packageName}.${entity.objectName}"
            }
            appendLine("        $qualifier.table,")
        }
        appendLine("    )")
        appendLine("}")
        entities.forEach { entity ->
            appendLine()
            append(emitCollection(entity, packageName))
        }
        inverses(entities).forEach { inverse ->
            appendLine()
            append(emitInverse(inverse, packageName))
        }
    }

/**
 * `db.todos` — the collection an application reads from.
 *
 * Generated rather than left to the application because it is the shape §4.5 is written in, and because
 * writing it by hand means writing the principal into it by hand.
 */
private fun emitCollection(entity: EntityModel, packageName: String): String = buildString {
    val qualifier = entity.objectQualified(packageName)
    appendLine("/** Every stored ${entity.simpleName} this principal may read. */")
    appendLine("context(principal: ${entity.principal})")
    appendLine("${entity.visibility} val jetlin.db.Db.${entity.collectionName}: jetlin.db.View<${entity.qualifiedName}>")
    appendLine("    get() = $qualifier.all(this)")
}

/**
 * The other side of a reference: `project.tasks`.
 *
 * Filtered by the *referencing* entity's policy, evaluated per read. That is what makes unsharing
 * reactive — a row that stops being readable leaves the collection, and the pages that iterated it
 * recompose, with no invalidation anywhere.
 */
private fun emitInverse(inverse: InverseModel, packageName: String): String = buildString {
    val source = inverse.source
    val qualifier = source.objectQualified(packageName)
    appendLine("/** Every ${source.simpleName} whose `${inverse.column}` is this one, and that this principal may read. */")
    appendLine("context(principal: ${source.principal})")
    appendLine("${inverse.visibility} val ${inverse.targetType}.${inverse.name}: jetlin.db.View<${source.qualifiedName}>")
    appendLine("    get() {")
    appendLine("        val target = this")
    appendLine("        val db = jetlin.db.databaseOf(target)")
    appendLine("        return jetlin.db.Gate.related(db, $qualifier.table, $qualifier.policy, principal) {")
    appendLine("            it.${inverse.column} == target")
    appendLine("        }")
    appendLine("    }")
}

internal data class InverseModel(
    val source: EntityModel,
    val targetType: String,
    val column: String,
    val name: String,
    val visibility: String,
)

/**
 * Every inverse relation worth generating.
 *
 * Named after the referencing entity — `project.tasks` — unless one entity references the same target
 * twice, in which case the column name disambiguates: two relations called `tasks` would be a compile
 * error on generated code, which is the worst kind.
 */
internal fun inverses(entities: List<EntityModel>): List<InverseModel> {
    val known = entities.associateBy { it.qualifiedName }
    return entities.flatMap { source ->
        val references = source.columns.filter { it.reference != null && it.reference in known }
        references.map { column ->
            val ambiguous = references.count { it.reference == column.reference } > 1
            val target = known.getValue(column.reference!!)
            InverseModel(
                source = source,
                targetType = target.qualifiedName,
                column = column.name,
                name = if (ambiguous) {
                    "${source.collectionName}By${column.name.replaceFirstChar(Char::uppercaseChar)}"
                } else {
                    source.collectionName
                },
                visibility = if (source.isInternal || target.isInternal) "internal" else "public",
            )
        }
    }
}

/**
 * The schema as data, for the migration tooling to diff against what is checked in.
 *
 * JSON written by hand because this module has no serialization dependency and the shape is five
 * fields deep. Sorted, so that reordering entity declarations does not show up as a schema change.
 */
internal fun emitSnapshot(entities: List<EntityModel>): String = buildString {
    val tableNames = entities.associate { it.qualifiedName to it.tableName }
    appendLine("{")
    appendLine("  \"version\": 1,")
    appendLine("  \"tables\": [")
    entities.sortedBy { it.tableName }.forEachIndexed { tableIndex, entity ->
        if (tableIndex > 0) appendLine("    },")
        appendLine("    {")
        appendLine("      \"name\": \"${entity.tableName}\",")
        appendLine("      \"entity\": \"${entity.qualifiedName}\",")
        appendLine("      \"columns\": [")
        appendLine("        { \"name\": \"id\", \"type\": \"INTEGER\", \"nullable\": false, \"primaryKey\": true }" +
            if (entity.columns.isEmpty()) "" else ",")
        entity.columns.sortedBy { it.name }.forEachIndexed { index, column ->
            val references = column.reference?.let { tableNames[it] }
            append("        { \"name\": \"${column.name}\", \"type\": \"${column.kind.sql}\"")
            append(", \"nullable\": ${column.nullable}")
            if (references != null) append(", \"references\": \"$references\"")
            if (column.owner) append(", \"owner\": true")
            append(" }")
            appendLine(if (index == entity.columns.lastIndex) "" else ",")
        }
        appendLine("      ]")
    }
    if (entities.isNotEmpty()) appendLine("    }")
    appendLine("  ]")
    appendLine("}")
}
