package jetlin.db.ksp

/**
 * Generates the table file for one entity.
 *
 * The generated code uses fully qualified names and no imports. Nobody reads it for style, and any
 * import could clash with a name declared in the entity's own file.
 *
 * Generation is plain string building, so unit tests can check the exact output. Compiling the
 * output would only show that it compiles, not that it's correct.
 */
internal fun emitTable(entity: EntityModel): String = buildString {
    val type = entity.qualifiedName
    appendLine("// Generated by jetlin-db-ksp from $type. Do not edit.")
    appendLine("@file:Suppress(\"RedundantVisibilityModifier\", \"unused\")")
    appendLine()
    if (entity.packageName.isNotEmpty()) {
        appendLine("package ${entity.packageName}")
        appendLine()
    }

    appendLine("/**")
    appendLine(" * The table for [$type], and the column objects a policy can refer to.")
    appendLine(" *")
    appendLine(" * They're the same column instances that the table writes, so `when (column)` in a policy matches them.")
    appendLine(" */")
    appendLine("${entity.visibility} object ${entity.objectName} {")
    appendLine()
    appendLine("    /** The access rules for [$type], from its companion object. */")
    appendLine("    ${entity.visibility} val policy: jetlin.db.Policy<$type, ${entity.principal}> = $type")
    appendLine()
    appendLine("    /** How [$type] is stored. */")
    appendLine("    ${entity.visibility} val table: jetlin.db.Table<$type> =")
    appendLine("        jetlin.db.table(\"${entity.tableName}\", $type::class) {")
    entity.columns.forEach { column -> appendLine("            ${declare(column)}") }
    appendLine("            load { row ->")
    appendLine(loadBody(entity).trimEnd().prependIndent("                "))
    appendLine("            }")
    appendLine("        }")
    entity.columns.forEach { column ->
        appendLine()
        appendLine("    /** The `${column.name}` column. */")
        appendLine("    ${entity.visibility} val ${column.name}: jetlin.db.Column<$type> =")
        appendLine("        table.column(\"${column.name}\")")
    }
    appendLine()
    append(emitAccessors(entity))
    appendLine("}")
    appendLine()
    append(emitDraft(entity))
    appendLine()
    append(emitMutators(entity))
}

/**
 * Generates the accessors that are application code's only way to obtain this entity's records.
 *
 * Each takes the principal as a context parameter. Code without a principal in scope fails to
 * compile, instead of running and reading records the user shouldn't see.
 */
private fun emitAccessors(entity: EntityModel): String = buildString {
    val type = entity.qualifiedName
    val principal = entity.principal
    appendLine("    /** Returns every stored ${entity.simpleName} that this principal can read. */")
    appendLine("    context(principal: $principal)")
    appendLine("    ${entity.visibility} fun all(db: jetlin.db.Db): jetlin.db.View<$type> =")
    appendLine("        jetlin.db.Gate.view(db, table, policy, principal)")
    appendLine()
    appendLine("    /** Returns the ${entity.simpleName} with [id], or `null` if it doesn't exist or this principal can't read it. */")
    appendLine("    context(principal: $principal)")
    appendLine("    ${entity.visibility} fun find(db: jetlin.db.Db, id: jetlin.db.Id<$type>): $type? =")
    appendLine("        jetlin.db.Gate.find(db, table, policy, principal, id)")
}

/**
 * Generates `update { }` and `delete()` as extension functions that take the principal.
 *
 * Direct assignment, such as `todo.done = true`, was considered and rejected. A property setter
 * can't take a context parameter, so it could only check a thread-local principal at runtime.
 * `update { }` is slightly longer to write, but it keeps the check at compile time.
 */
private fun emitMutators(entity: EntityModel): String = buildString {
    val type = entity.qualifiedName
    val principal = entity.principal
    appendLine("/**")
    appendLine(" * Changes this ${entity.simpleName} in one transaction, which is committed to disk before any session sees the change.")
    appendLine(" *")
    appendLine(" * A refused write throws [jetlin.db.AccessDenied] and rolls back the whole transaction.")
    appendLine(" */")
    appendLine("context(principal: $principal)")
    appendLine("${entity.visibility} fun $type.update(block: ${entity.draftQualified}.() -> Unit): Unit =")
    appendLine("    jetlin.db.Gate.update(this, ${entity.objectQualified}.policy, principal, ${entity.draftQualified}(this), block)")
    appendLine()
    appendLine("/** Deletes this ${entity.simpleName}, if this principal can delete it. Otherwise, throws [jetlin.db.AccessDenied]. */")
    appendLine("context(principal: $principal)")
    appendLine("${entity.visibility} fun $type.delete(): Unit =")
    appendLine("    jetlin.db.Gate.delete(this, ${entity.objectQualified}.policy, principal)")
    appendLine()
    appendLine("/** Returns whether this principal can change this ${entity.simpleName}: whether [update] gets past its record-level check. */")
    appendLine("context(principal: $principal)")
    appendLine("${entity.visibility} fun $type.canUpdate(): Boolean =")
    appendLine("    jetlin.db.Gate.canUpdate(this, ${entity.objectQualified}.policy, principal)")
    appendLine()
    appendLine("/** Returns whether this principal can set [column] of this ${entity.simpleName} in [update]. */")
    appendLine("context(principal: $principal)")
    appendLine("${entity.visibility} fun $type.canUpdate(column: jetlin.db.Column<$type>): Boolean =")
    appendLine("    jetlin.db.Gate.canUpdate(this, column, ${entity.objectQualified}.policy, principal)")
    appendLine()
    appendLine("/** Returns whether this principal can delete this ${entity.simpleName}: whether [delete] would succeed. */")
    appendLine("context(principal: $principal)")
    appendLine("${entity.visibility} fun $type.canDelete(): Boolean =")
    appendLine("    jetlin.db.Gate.canDelete(this, ${entity.objectQualified}.policy, principal)")
    entity.transferableOwner?.let { owner ->
        appendLine()
        appendLine("/** Makes [to] the owner of this ${entity.simpleName}, if the policy's `canTransfer` allows it. Otherwise, throws [jetlin.db.AccessDenied]. */")
        appendLine("context(principal: $principal)")
        appendLine("${entity.visibility} fun $type.transferTo(to: $principal): Unit =")
        appendLine("    jetlin.db.Gate.transfer(this, to, ${entity.objectQualified}.policy, principal) { ${owner.name} = it }")
        appendLine()
        appendLine("/** Returns whether this principal can make [to] the owner of this ${entity.simpleName}: whether [transferTo] would succeed. */")
        appendLine("context(principal: $principal)")
        appendLine("${entity.visibility} fun $type.canTransferTo(to: $principal): Boolean =")
        appendLine("    jetlin.db.Gate.canTransfer(this, to, ${entity.objectQualified}.policy, principal)")
    }
}

/** Returns the table builder call that declares [column]. */
private fun declare(column: ColumnModel): String {
    val nullable = ", nullable = ${column.nullable}"
    val get = "{ it.${column.name} }"
    return when {
        column.reference != null ->
            "reference(\"${column.name}\", ${column.reference}::class$nullable) $get"
        column.kind == SqlKind.Text -> "text(\"${column.name}\"$nullable) $get"
        column.kind == SqlKind.Bool -> "bool(\"${column.name}\"$nullable) $get"
        column.kind == SqlKind.Real -> "real(\"${column.name}\"$nullable) $get"
        else -> "integer(\"${column.name}\"$nullable) $get"
    }
}

/** Returns the expression that reads [column] from a stored row. */
private fun read(column: ColumnModel): String {
    val name = "\"${column.name}\""
    return when {
        column.reference != null -> when {
            column.nullable -> "row.referenceOrNull($name, ${column.reference}::class)"
            else -> "row.reference($name, ${column.reference}::class)"
        }
        column.kind == SqlKind.Text -> if (column.nullable) "row.stringOrNull($name)" else "row.string($name)"
        column.kind == SqlKind.Bool ->
            if (column.nullable) "row.booleanOrNull($name)" else "row.boolean($name)"
        column.kind == SqlKind.Real -> when (column.baseType) {
            "kotlin.Float" ->
                if (column.nullable) "row.doubleOrNull($name)?.toFloat()" else "row.double($name).toFloat()"
            else -> if (column.nullable) "row.doubleOrNull($name)" else "row.double($name)"
        }
        else -> when (column.baseType) {
            "kotlin.Int" -> if (column.nullable) "row.intOrNull($name)" else "row.int($name)"
            else -> if (column.nullable) "row.longOrNull($name)" else "row.long($name)"
        }
    }
}

/**
 * Generates the code that recreates a record from a row: the constructor call, followed by
 * assignments for columns the constructor doesn't take.
 *
 * Columns with a matching constructor parameter are passed to the constructor, which is what makes
 * immutable columns and `val` cells loadable. The other columns must be settable, and [validate]
 * has already checked that.
 */
private fun loadBody(entity: EntityModel): String = buildString {
    val byConstructor = entity.columns.filter { it.constructorParameter }
    val afterwards = entity.columns.filterNot { it.constructorParameter }

    append(entity.qualifiedName).appendLine("(")
    byConstructor.forEach { column -> appendLine("    ${column.name} = ${read(column)},") }
    append(")")
    if (afterwards.isEmpty()) {
        appendLine()
    } else {
        appendLine(".also { entity ->")
        afterwards.forEach { column -> appendLine("    entity.${column.name} = ${read(column)}") }
        appendLine("}")
    }
}

/**
 * Generates the draft type that `update { }` passes to its block.
 *
 * Only settable columns are included. Immutable columns are written once on insert and can't
 * change. Each setter records its value in the `Draft` base class instead of writing the record, so
 * `Gate.update` can check every column against the record as it was before the block, and then
 * check the finished record. That's why drafts exist instead of assigning to the record directly.
 */
private fun emitDraft(entity: EntityModel): String = buildString {
    val settable = entity.columns.filter { it.settable }
    appendLine("/**")
    appendLine(" * The fields of a [${entity.qualifiedName}] that `update { }` can set.")
    appendLine(" *")
    appendLine(" * Setting a field records the value, and reading it back returns what was set. The record itself")
    appendLine(" * changes only after the whole block has been checked.")
    appendLine(" */")
    appendLine("${entity.visibility} class ${entity.draftName} internal constructor(")
    appendLine("    private val record: ${entity.qualifiedName},")
    appendLine(") : jetlin.db.Draft<${entity.qualifiedName}>() {")
    settable.forEachIndexed { index, column ->
        if (index > 0) appendLine()
        appendLine("    /** Sets `${column.name}` once the block is done, if this principal can write it. Otherwise, the update throws [jetlin.db.AccessDenied]. */")
        appendLine("    ${entity.visibility} var ${column.name}: ${column.declaredType}")
        appendLine("        get() = read(${entity.objectName}.${column.name}, record.${column.name})")
        appendLine("        set(value) {")
        appendLine("            write(${entity.objectName}.${column.name}, value) { record.${column.name} = it }")
        appendLine("        }")
    }
    if (settable.isEmpty()) {
        appendLine("    // ${entity.simpleName} has no settable columns. All of them are written on insert.")
    }
    appendLine("}")
}

/**
 * Generates the schema object listing every table in load order.
 *
 * Applications pass this list to `Db.open`. Because it's generated, nobody has to maintain the order
 * that non-null references require by hand.
 */
internal fun emitSchema(entities: List<EntityModel>, packageName: String, objectName: String): String =
    buildString {
        appendLine("// Generated by jetlin-db-ksp. Do not edit.")
        appendLine("@file:Suppress(\"RedundantVisibilityModifier\", \"unused\")")
        appendLine()
        if (packageName.isNotEmpty()) {
            appendLine("package $packageName")
            appendLine()
        }
        val visibility = if (entities.any { it.isInternal }) "internal" else "public"
        appendLine("/**")
        appendLine(" * All stored entities, ordered so that each table is loaded after the tables it references.")
        appendLine(" */")
        appendLine("$visibility object $objectName {")
        appendLine("    /** The tables, in load order. Pass them to [jetlin.db.Db.open]. */")
        appendLine("    $visibility val tables: List<jetlin.db.Table<out jetlin.db.Record>> = listOf(")
        entities.forEach { entity ->
            val qualifier = if (entity.packageName == packageName || entity.packageName.isEmpty()) {
                entity.objectName
            } else {
                "${entity.packageName}.${entity.objectName}"
            }
            appendLine("        $qualifier.table,")
        }
        appendLine("    )")
        appendLine("}")
        entities.forEach { entity ->
            appendLine()
            append(emitCollection(entity, packageName))
        }
        inverses(entities).forEach { inverse ->
            appendLine()
            append(emitInverse(inverse, packageName))
        }
    }

/**
 * Generates the collection accessor an application reads from, such as `db.todos`.
 *
 * It's generated so that the principal parameter is always present. This is the accessor shape that
 * §4.5 of the design plan describes.
 */
private fun emitCollection(entity: EntityModel, packageName: String): String = buildString {
    val qualifier = entity.objectQualified(packageName)
    appendLine("/** Every stored ${entity.simpleName} that this principal can read. */")
    appendLine("context(principal: ${entity.principal})")
    appendLine("${entity.visibility} val jetlin.db.Db.${entity.collectionName}: jetlin.db.View<${entity.qualifiedName}>")
    appendLine("    get() = $qualifier.all(this)")
}

/**
 * Generates the inverse side of a reference, such as `project.tasks`.
 *
 * The collection is filtered by the policy of the referencing entity, on every read. That makes
 * unsharing reactive: a record that's no longer readable drops out of the collection, and pages that
 * iterated it recompose without any invalidation code.
 */
private fun emitInverse(inverse: InverseModel, packageName: String): String = buildString {
    val source = inverse.source
    val qualifier = source.objectQualified(packageName)
    appendLine("/** The ${source.simpleName} records whose `${inverse.column}` is this record, and that this principal can read. */")
    appendLine("context(principal: ${source.principal})")
    appendLine("${inverse.visibility} val ${inverse.targetType}.${inverse.name}: jetlin.db.View<${source.qualifiedName}>")
    appendLine("    get() {")
    appendLine("        val target = this")
    appendLine("        val db = jetlin.db.databaseOf(target)")
    appendLine("        return jetlin.db.Gate.related(db, $qualifier.table, $qualifier.policy, principal) {")
    appendLine("            it.${inverse.column} == target")
    appendLine("        }")
    appendLine("    }")
}

/**
 * An inverse relation to generate.
 *
 * @property source the referencing entity.
 * @property targetType the qualified name of the referenced entity, which gets the property.
 * @property column the referencing column.
 * @property name the property name.
 * @property visibility the property's visibility modifier.
 */
internal data class InverseModel(
    val source: EntityModel,
    val targetType: String,
    val column: String,
    val name: String,
    val visibility: String,
)

/**
 * Lists the inverse relations to generate.
 *
 * Each is named after the referencing entity, as in `project.tasks`. If an entity references the
 * same target through two columns, the column name is added to tell them apart. Otherwise there
 * would be two properties called `tasks`, and the generated code would fail to compile in a way
 * that's hard for the user to fix.
 */
internal fun inverses(entities: List<EntityModel>): List<InverseModel> {
    val known = entities.associateBy { it.qualifiedName }
    return entities.flatMap { source ->
        val references = source.columns.filter { it.reference != null && it.reference in known }
        references.map { column ->
            val ambiguous = references.count { it.reference == column.reference } > 1
            val target = known.getValue(column.reference!!)
            InverseModel(
                source = source,
                targetType = target.qualifiedName,
                column = column.name,
                name = if (ambiguous) {
                    "${source.collectionName}By${column.name.replaceFirstChar(Char::uppercaseChar)}"
                } else {
                    source.collectionName
                },
                visibility = if (source.isInternal || target.isInternal) "internal" else "public",
            )
        }
    }
}

/**
 * Generates the schema as JSON, which the migration tooling compares with the checked-in snapshot.
 *
 * The JSON is written by hand, because this module has no serialization dependency, and the
 * structure is small. Tables and columns are sorted, so reordering entity declarations doesn't show up
 * as a schema change.
 */
internal fun emitSnapshot(entities: List<EntityModel>): String = buildString {
    val tableNames = entities.associate { it.qualifiedName to it.tableName }
    appendLine("{")
    appendLine("  \"version\": 1,")
    appendLine("  \"tables\": [")
    entities.sortedBy { it.tableName }.forEachIndexed { tableIndex, entity ->
        if (tableIndex > 0) appendLine("    },")
        appendLine("    {")
        appendLine("      \"name\": \"${entity.tableName}\",")
        appendLine("      \"entity\": \"${entity.qualifiedName}\",")
        appendLine("      \"columns\": [")
        appendLine("        { \"name\": \"id\", \"type\": \"INTEGER\", \"nullable\": false, \"primaryKey\": true }" +
            if (entity.columns.isEmpty()) "" else ",")
        entity.columns.sortedBy { it.name }.forEachIndexed { index, column ->
            val references = column.reference?.let { tableNames[it] }
            append("        { \"name\": \"${column.name}\", \"type\": \"${column.kind.sql}\"")
            append(", \"nullable\": ${column.nullable}")
            if (references != null) append(", \"references\": \"$references\"")
            if (column.owner) append(", \"owner\": true")
            append(" }")
            appendLine(if (index == entity.columns.lastIndex) "" else ",")
        }
        appendLine("      ]")
    }
    if (entities.isNotEmpty()) appendLine("    }")
    appendLine("  ]")
    appendLine("}")
}
