package jetlin.db

/**
 * The entities the tests in this module are written against.
 *
 * Between them they cover the three access shapes of §4.3 — owner-only, shared by a property of a
 * related record, and readable by many with one column restricted — because those are the shapes the
 * design claims to cover and a claim with no example is a guess.
 *
 * Their tables, column objects, drafts and gated accessors are generated by `:jetlin-db-ksp`.
 */
@Entity
internal class User(name: String, admin: Boolean = false) : Record(), Principal {
    var name: String by column(name)
    var admin: Boolean by column(admin)

    companion object : Policy<User, User> {
        override fun canRead(record: User, principal: User): Boolean = true

        /** Anyone may rename themselves; only an admin may rename anyone else. */
        override fun canWrite(record: User, principal: User): Boolean = record == principal || principal.admin
    }
}

@Entity
internal class Project(
    @Owner val owner: User,
    name: String,
    shared: Boolean = false,
) : Record() {
    var name: String by column(name)
    var shared: Boolean by column(shared)

    companion object : Policy<Project, User> {
        override fun canRead(record: Project, principal: User): Boolean =
            record.owner == principal || record.shared
        override fun canWrite(record: Project, principal: User): Boolean = record.owner == principal
    }
}

@Entity
internal class Task(
    @Owner val owner: User,
    title: String,
    done: Boolean = false,
) : Record() {
    var title: String by column(title)
    var done: Boolean by column(done)
    var archived: Boolean by column(false)
    var project: Project? by reference()

    companion object : Policy<Task, User> {
        /**
         * Shared by a property of a related record: whoever owns it, plus anyone at all once its project
         * is shared.
         *
         * `record.project?.shared` reads a live cell of another record, which is what makes sharing and
         * unsharing reactive rather than something to invalidate.
         */
        override fun canRead(record: Task, principal: User): Boolean =
            record.owner == principal || record.project?.shared == true

        override fun canWrite(record: Task, principal: User): Boolean = record.owner == principal

        /** Read by many, and one column only an admin may touch. */
        override fun canWrite(record: Task, column: Column<Task>, principal: User): Boolean = when (column) {
            Tasks.archived -> principal.admin
            else -> canWrite(record, principal)
        }
    }
}

/** The generated schema, in generated load order. */
internal fun schema(): List<Table<out Record>> = JetlinSchema.tables
