package jetlin.db.gradle

/**
 * A marker line that stops `dbMigrate` from running a destructive migration until someone has read it.
 *
 * The generator adds it to every migration that loses data, and deleting it is how the author
 * confirms the migration. That confirmation is an edit to a file and shows up in code review, unlike a
 * command-line flag, which leaves no trace.
 */
public const val ACKNOWLEDGEMENT_MARKER: String = "-- jetlin-db:unacknowledged"

/** Suffix for the temporary table a rebuild creates before replacing the original. */
private const val REBUILD_SUFFIX = "__jetlin_new"

/**
 * Generates the SQL for a migration.
 *
 * The output is meant to be read and, where needed, edited before it is committed. Decisions that
 * can't be derived from the schema, such as the value to backfill into a new required column or how
 * to convert a column whose type changed, appear as visible SQL instead of being hidden behind options.
 *
 * ## Table rebuilds
 *
 * SQLite's `ALTER TABLE` can only add, drop and rename columns and rename tables. Changing a column's
 * type, nullability or foreign key requires creating a new table, copying the rows, dropping the old
 * table and renaming the new one. SQLite documents this as a twelve-step procedure. This function
 * generates the SQL steps. The steps that need a live connection (disabling foreign keys, running a
 * transaction, `PRAGMA foreign_key_check`, and checking that no index, trigger or view was lost) are
 * done by the runner; see [Migrations].
 */
public fun migrationSql(from: SchemaFile, to: SchemaFile, changes: List<Change>): String = buildString {
    appendLine("-- Generated by jetlin-db. Review it, edit it if needed, then commit it.")
    appendLine("--")
    appendLine("-- Changes:")
    changes.forEach { appendLine("--   * ${it.summary}") }

    val destructive = changes.filter { it.destructive }
    if (destructive.isNotEmpty()) {
        appendLine("--")
        appendLine("-- This migration is destructive:")
        destructive.forEach { appendLine("--   ! ${it.summary}") }
        appendLine("--")
        appendLine("-- dbMigrate will not run this migration until you review it and delete the next line.")
        appendLine(ACKNOWLEDGEMENT_MARKER)
    }
    appendLine()

    val rebuilt = changes.filter { needsRebuild(it) }.mapTo(mutableSetOf()) { tableOf(it) }

    for (change in changes) {
        if (tableOf(change) in rebuilt && change !is Change.AddTable && change !is Change.DropTable) {
            continue // The table rebuild below already brings every column to its declared definition.
        }
        when (change) {
            is Change.AddTable -> {
                appendLine(createTable(change.table))
                appendLine()
            }
            is Change.DropTable -> {
                appendLine("DROP TABLE ${change.table.name};")
                appendLine()
            }
            is Change.AddColumn -> {
                appendLine("ALTER TABLE ${change.table} ADD COLUMN ${addedColumn(change.column)};")
                appendLine()
            }
            is Change.DropColumn -> {
                appendLine("ALTER TABLE ${change.table} DROP COLUMN ${change.column.name};")
                appendLine()
            }
            is Change.AlterColumn -> Unit // Always handled by a table rebuild.
        }
    }

    for (table in rebuilt.sorted()) {
        val target = to.table(table) ?: continue
        appendLine(rebuild(from.table(table), target))
        appendLine()
    }
}.trimEnd() + "\n"

private fun tableOf(change: Change): String = when (change) {
    is Change.AddTable -> change.table.name
    is Change.DropTable -> change.table.name
    is Change.AddColumn -> change.table
    is Change.DropColumn -> change.table
    is Change.AlterColumn -> change.table
}

/**
 * Whether this change requires rebuilding the table.
 *
 * Changing a column's type, nullability or foreign key does. So does adding a *required* reference to
 * an existing table, because SQLite only adds a column with a foreign key if its default is NULL.
 */
private fun needsRebuild(change: Change): Boolean = when (change) {
    is Change.AlterColumn -> true
    is Change.AddColumn -> !change.column.nullable && change.column.references != null
    else -> false
}

private fun createTable(table: TableSchema, name: String = table.name): String = buildString {
    appendLine("CREATE TABLE $name (")
    append(table.columns.joinToString(",\n") { "  ${it.definition()}" })
    appendLine()
    append(");")
}

/** A column definition for `ALTER TABLE … ADD COLUMN`. Required columns get a constant default, which SQLite requires. */
private fun addedColumn(column: ColumnSchema): String = buildString {
    append(column.definition())
    if (!column.nullable) append(" DEFAULT ").append(column.backfill())
}

/**
 * Generates a table rebuild: create a new table, copy the rows, drop the old table and rename the new one.
 *
 * Existing columns keep their values. New columns are filled with [ColumnSchema.backfill], which is a
 * best guess that appears in the generated SQL for the author to review.
 */
private fun rebuild(before: TableSchema?, after: TableSchema): String = buildString {
    val temporary = "${after.name}$REBUILD_SUFFIX"
    appendLine("-- ${after.name} cannot be altered in place, because SQLite's ALTER TABLE can't change a")
    appendLine("-- column's type, nullability or foreign key. The table is rebuilt: create, copy, drop, rename.")
    appendLine(createTable(after, temporary))
    appendLine()
    appendLine("INSERT INTO $temporary (${after.columns.joinToString { it.name }})")
    appendLine("SELECT")
    val values = after.columns.map { column ->
        val existed = before?.column(column.name) != null
        if (existed) "  ${column.name}" else "  ${column.backfill()} AS ${column.name}"
    }
    appendLine(values.joinToString(",\n"))
    appendLine("FROM ${after.name};")
    appendLine()
    appendLine("DROP TABLE ${after.name};")
    append("ALTER TABLE $temporary RENAME TO ${after.name};")
}
