package jetlin.db.gradle

/**
 * The line that stops `dbMigrate` running a migration nobody has read.
 *
 * Generated into any migration that loses data. Deleting it is the acknowledgement — a deliberate edit to
 * a file in a review, rather than a flag on a command line that nobody sees afterwards.
 */
public const val ACKNOWLEDGEMENT_MARKER: String = "-- jetlin-db:unacknowledged"

/** Suffix for the table a rebuild builds alongside the one it is replacing. */
private const val REBUILD_SUFFIX = "__jetlin_new"

/**
 * The SQL for one migration.
 *
 * Generated, and then read and edited by a human: everything that cannot be known from the schema alone —
 * what to backfill a new required column with, how to transform a value whose type changed — is present as
 * SQL rather than hidden behind a flag.
 *
 * ## Why some changes become a whole new table
 *
 * SQLite's `ALTER TABLE` can add a column, drop a column, rename a column and rename a table. Anything
 * else — a type, a nullability, a foreign key — requires building a new table, copying the rows, dropping
 * the old one and renaming. That is the procedure SQLite documents in twelve steps; the steps that need a
 * live connection (turning foreign keys off, the transaction, `PRAGMA foreign_key_check`, and checking
 * that no index, trigger or view was lost) belong to the runner, which has one. See [Migrations].
 */
public fun migrationSql(from: SchemaFile, to: SchemaFile, changes: List<Change>): String = buildString {
    appendLine("-- Generated by jetlin-db. Read it, edit it if it needs editing, and commit it.")
    appendLine("--")
    appendLine("-- Changes:")
    changes.forEach { appendLine("--   * ${it.summary}") }

    val destructive = changes.filter { it.destructive }
    if (destructive.isNotEmpty()) {
        appendLine("--")
        appendLine("-- This migration is destructive:")
        destructive.forEach { appendLine("--   ! ${it.summary}") }
        appendLine("--")
        appendLine("-- Delete the next line once you have read what it does. Until then dbMigrate refuses it.")
        appendLine(ACKNOWLEDGEMENT_MARKER)
    }
    appendLine()

    val rebuilt = changes.filter { needsRebuild(it) }.mapTo(mutableSetOf()) { tableOf(it) }

    for (change in changes) {
        if (tableOf(change) in rebuilt && change !is Change.AddTable && change !is Change.DropTable) {
            continue // Covered by the rebuild, which brings the whole table to its declared shape.
        }
        when (change) {
            is Change.AddTable -> {
                appendLine(createTable(change.table))
                appendLine()
            }
            is Change.DropTable -> {
                appendLine("DROP TABLE ${change.table.name};")
                appendLine()
            }
            is Change.AddColumn -> {
                appendLine("ALTER TABLE ${change.table} ADD COLUMN ${addedColumn(change.column)};")
                appendLine()
            }
            is Change.DropColumn -> {
                appendLine("ALTER TABLE ${change.table} DROP COLUMN ${change.column.name};")
                appendLine()
            }
            is Change.AlterColumn -> Unit // Always part of a rebuild.
        }
    }

    for (table in rebuilt.sorted()) {
        val target = to.table(table) ?: continue
        appendLine(rebuild(from.table(table), target))
        appendLine()
    }
}.trimEnd() + "\n"

private fun tableOf(change: Change): String = when (change) {
    is Change.AddTable -> change.table.name
    is Change.DropTable -> change.table.name
    is Change.AddColumn -> change.table
    is Change.DropColumn -> change.table
    is Change.AlterColumn -> change.table
}

/**
 * Whether this change can be done in place.
 *
 * A column's type, nullability or foreign key cannot. Nor can a *required* reference arriving on an
 * existing table: SQLite will only add a column with a foreign key if its default is null.
 */
private fun needsRebuild(change: Change): Boolean = when (change) {
    is Change.AlterColumn -> true
    is Change.AddColumn -> !change.column.nullable && change.column.references != null
    else -> false
}

private fun createTable(table: TableSchema, name: String = table.name): String = buildString {
    appendLine("CREATE TABLE $name (")
    append(table.columns.joinToString(",\n") { "  ${it.definition()}" })
    appendLine()
    append(");")
}

/** `ALTER TABLE … ADD COLUMN` needs a default for a required column, and SQLite needs it to be constant. */
private fun addedColumn(column: ColumnSchema): String = buildString {
    append(column.definition())
    if (!column.nullable) append(" DEFAULT ").append(column.backfill())
}

/**
 * The rebuild: a new table, the rows copied across, the old one dropped, the new one renamed.
 *
 * Columns that existed keep their values. Columns that did not are filled with [ColumnSchema.backfill],
 * which is a guess sitting in plain sight in the generated SQL.
 */
private fun rebuild(before: TableSchema?, after: TableSchema): String = buildString {
    val temporary = "${after.name}$REBUILD_SUFFIX"
    appendLine("-- ${after.name} cannot be altered in place: SQLite's ALTER TABLE does not change a")
    appendLine("-- column's type, its nullability or its foreign key. Rebuild, copy, drop, rename.")
    appendLine(createTable(after, temporary))
    appendLine()
    appendLine("INSERT INTO $temporary (${after.columns.joinToString { it.name }})")
    appendLine("SELECT")
    val values = after.columns.map { column ->
        val existed = before?.column(column.name) != null
        if (existed) "  ${column.name}" else "  ${column.backfill()} AS ${column.name}"
    }
    appendLine(values.joinToString(",\n"))
    appendLine("FROM ${after.name};")
    appendLine()
    appendLine("DROP TABLE ${after.name};")
    append("ALTER TABLE $temporary RENAME TO ${after.name};")
}
