-- Generated by jetlin-db. Read it, edit it if it needs editing, and commit it.
--
-- Changes:
--   * add table notes
--   * add table teams
--   * add table todos
--   * add table users

CREATE TABLE notes (
  id INTEGER PRIMARY KEY,
  owner INTEGER NOT NULL REFERENCES users(id),
  text TEXT NOT NULL
);

CREATE TABLE teams (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE todos (
  id INTEGER PRIMARY KEY,
  archived INTEGER NOT NULL,
  done INTEGER NOT NULL,
  owner INTEGER NOT NULL REFERENCES users(id),
  team INTEGER REFERENCES teams(id),
  title TEXT NOT NULL
);

CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  admin INTEGER NOT NULL,
  email TEXT NOT NULL,
  name TEXT NOT NULL,
  team INTEGER REFERENCES teams(id)
);
